server:
  port: 8080
  servlet:
    context-path: /
spring:
  datasource:
    url: jdbc:mysql://localhost:3307/cube_mall?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  type-aliases-package: com.cube.webadmin.po
  mapper-locations: classpath:mapper/*.xml
mapper:
  identity: MYSQL

mall:
  rateLimit:
    enable: true
  loginTimeLimit: 10
  loginAfterTime: 10
  saveLoginTime: 7
  tokenExpireTime: 7

