eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 10500
spring:
  application:
    name: mall-zuul
zuul:
  routes:
    api-a:
      path: /api-product/**
      serviceId: product-center
    api-b:
      path: /api-order/**
      serviceId: order-center


## 需要解密的url 这里做测试
ecyrypt:
  urls[0]: /api-product/brands/