server:
  port: 10540
spring:
  application:
    name: pay-center
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
jasypt:
  encryptor:
    password: bfcb82076aa849588389c7eb121d6af2

